// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ctwgxtfbbveguhoodgrt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0d2d4dGZiYnZlZ3Vob29kZ3J0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4Mjk2OTAsImV4cCI6MjA3NDQwNTY5MH0.lQLS6WwY8V0biSNrvT_CCkt41VACRUZDUYSE4PuxDTY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});